/**
 * Guardrail Agent
 *
 * Monitors all other active agents. Loads rules from the risk profile
 * generated by the risk scanner. Operates in alert or intervene mode.
 *
 * Deployed as a Vercel serverless function.
 * Other agents POST their activity here. This agent evaluates it and acts.
 *
 * Customize: set MODE, adjust BASELINE_RULES, point ALERT_DESTINATION at your channel.
 */

import fs from 'fs';
import path from 'path';
import { getCorrelationId, correlatedLogger } from '../../lib/correlation.js';

// Customize: 'alert' logs and notifies. 'intervene' can block or reroute.
const MODE = process.env.GUARDRAIL_MODE || 'alert'; // 'alert' | 'intervene'

const ALERT_DESTINATION = process.env.ALERT_WEBHOOK_URL; // Slack, PagerDuty, etc.
const INTERNAL_TOKEN    = process.env.INTERNAL_AGENT_TOKEN;

if (!INTERNAL_TOKEN) {
  throw new Error('[guardrail] INTERNAL_AGENT_TOKEN env var is required');
}

// Escalation: how many alerts in ESCALATION_WINDOW_MS before raising severity
const ESCALATION_THRESHOLD  = parseInt(process.env.ESCALATION_THRESHOLD || '5', 10);
const ESCALATION_WINDOW_MS  = 60_000;

// In-memory alert counter (use KV store for persistence across invocations)
const alertCounts = new Map();

// ─── Rule definitions ───────────────────────────────────────────────────────
//
// BASELINE_RULES apply to every agent on every platform.
// Customize: add platform-specific rules below them.

const BASELINE_RULES = [
  {
    id: 'credential-exposure',
    description: 'Block any agent exposing credentials or tokens in output',
    severity: 'critical',
    test: (activity) => {
      const str = JSON.stringify(activity.output || {});
      return /api[_-]?key|bearer\s+\S+|password\s*[:=]/i.test(str);
    },
    intervene: true, // Always intervene regardless of MODE
  },
  {
    id: 'scope-violation',
    description: 'Agent accessed a resource outside its defined scope',
    severity: 'high',
    test: (activity) =>
      activity.accessed_resource &&
      activity.allowed_resources &&
      !activity.allowed_resources.includes(activity.accessed_resource),
    intervene: false,
  },
  {
    id: 'repeated-failed-calls',
    description: 'Repeated identical failed calls - possible loop or broken dependency',
    severity: 'high',
    test: (activity) => activity.consecutive_failures >= 3,
    intervene: false,
  },
  {
    id: 'silent-failure',
    description: 'Unhandled exception that did not surface an error',
    severity: 'medium',
    test: (activity) => activity.silent_failure === true,
    intervene: false,
  },
  {
    id: 'unexpected-activation',
    description: 'Agent became active without a recorded activation event',
    severity: 'high',
    test: (activity) => activity.event_type === 'agent.activated' && !activity.activation_recorded,
    intervene: false,
  },
];

// Customize: additional rules derived from risk scanner output
function loadRiskProfileRules() {
  try {
    const profilePath = path.join(process.cwd(), 'risk-scanner/output/risk-profile.json');
    const profile = JSON.parse(fs.readFileSync(profilePath, 'utf8'));

    // Customize: map your risk profile findings into rule objects
    return (profile.findings || [])
      .filter((f) => f.severity === 'critical' || f.severity === 'high')
      .map((finding) => {
        const rawId = finding.guardrail_rule || finding.location || finding.category || 'unknown';
        const ruleId = `risk-${String(rawId).replace(/\s+/g, '-').toLowerCase()}`;
        return {
          id: ruleId,
          description: finding.description,
          severity: finding.severity,
          test: (activity) => {
            const matchesEventType =
              !!finding.category &&
              activity.event_type === finding.category;
            const matchesLocation =
              !!finding.location &&
              typeof activity.accessed_resource === 'string' &&
              activity.accessed_resource.includes(finding.location);
            return matchesEventType || matchesLocation;
          },
          intervene: finding.severity === 'critical',
        };
      });
  } catch {
    // Risk profile not yet generated - baseline rules still apply
    return [];
  }
}

const ALL_RULES = [...BASELINE_RULES, ...loadRiskProfileRules()];

// ─── Alert and intervention logic ─────────────────────────────────────────

function countAlert(agentId) {
  const now = Date.now();
  const entry = alertCounts.get(agentId) || { count: 0, windowStart: now };
  if (now - entry.windowStart > ESCALATION_WINDOW_MS) {
    entry.count = 1;
    entry.windowStart = now;
  } else {
    entry.count++;
  }
  alertCounts.set(agentId, entry);
  return entry.count;
}

async function sendAlert(rule, activity, count, log) {
  const escalated = count >= ESCALATION_THRESHOLD;
  const payload = {
    rule_id: rule.id,
    description: rule.description,
    severity: escalated ? 'critical' : rule.severity,
    escalated,
    agent_id: activity.agent_id,
    timestamp: new Date().toISOString(),
    activity_summary: {
      event_type: activity.event_type,
      accessed_resource: activity.accessed_resource,
    },
  };

  log.log('ALERT:', JSON.stringify(payload));

  if (ALERT_DESTINATION) {
    try {
      await fetch(ALERT_DESTINATION, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
    } catch (err) {
      log.error('failed to send alert:', err.message);
    }
  }

  return payload;
}

// Customize: add actual intervention logic - pause an agent, revoke a token, etc.
async function intervene(rule, activity, log) {
  log.warn(`INTERVENING on rule "${rule.id}" for agent "${activity.agent_id}"`);
  // Customize: call your agent registry to pause or reroute the offending agent
  // e.g. await fetch(`${AGENT_REGISTRY_URL}/pause/${activity.agent_id}`, { method: 'POST' })
  return { action: 'paused', agent_id: activity.agent_id, rule_id: rule.id };
}

// ─── Vercel serverless handler ─────────────────────────────────────────────

export default async function handler(req, res) {
  // Guardrail accepts both raw activity reports and enveloped agent-bus messages
  const correlationId = getCorrelationId(req);
  const log = correlatedLogger(correlationId, 'guardrail');

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // Verify the report is from a trusted internal source
  if (!INTERNAL_TOKEN || req.headers['authorization'] !== `Bearer ${INTERNAL_TOKEN}`) {
    return res.status(401).json({ error: 'Unauthorized' });
  }

  // Support both direct activity posts and agent-bus enveloped messages
  const body = req.body;
  const activity = body?.envelope ? body.payload : body;

  if (!activity || !activity.agent_id) {
    return res.status(400).json({ error: 'activity.agent_id is required' });
  }

  const triggered = [];

  for (const rule of ALL_RULES) {
    let matched = false;
    try { matched = rule.test(activity); } catch (err) { log.warn(`rule "${rule.id}" threw during evaluation:`, err.message); }

    if (matched) {
      const alertCount = countAlert(activity.agent_id);
      const alert = await sendAlert(rule, activity, alertCount, log);

      const shouldIntervene = rule.intervene || (MODE === 'intervene' && rule.severity === 'high');
      let intervention = null;
      if (shouldIntervene) {
        intervention = await intervene(rule, activity, log);
      }

      triggered.push({ rule_id: rule.id, alert, intervention });
    }
  }

  if (triggered.length > 0) {
    log.warn(`${triggered.length} rule(s) triggered for agent "${activity.agent_id}"`);
  }

  return res.status(200).json({
    evaluated: ALL_RULES.length,
    triggered: triggered.length,
    mode: MODE,
    correlation_id: correlationId,
    results: triggered,
  });
}
